config/routes.rb
Rails.application.routes.draw do
  get 'users/show'
  devise_for :users, controllers: {   registrations: 'users/registrations',sessions: 'users/sessions' }
  root to: "posts#index" 
  get "posts/game"
  get 'posts/cooking'
  resources :posts, only: [:new, :create, :show, :edit, :update, :destroy] do
    resources :comments, only: [:create]
  end
  resources :users, only: [:show]
end

app/models/post.rb
class Post < ApplicationRecord
  extend ActiveHash::Associations::ActiveRecordExtensions
  belongs_to_active_hash :genre
  belongs_to :user
  has_many :comments, dependent: :destroy
  has_one_attached :image

  with_options presence: true do
    validates :title
    validates :description
    validates :genre_id
  end

  with_options numericality: { other_than: 1 } do
    validates :genre_id
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def index
    @post = Post.all
  end

  def new
    @post = Post.new
  end

  def create
    @post = Post.new(post_params)
    if @post.save
      redirect_to root_path
    else
      render :new
    end
  end

  def show
    @post = Post.find(params[:id])
    @comment = Comment.new
    @comments = @post.comments.includes(:user)
  end

  def edit
    @post = Post.find(params[:id])
  end

  def update
    @post = Post.find(params[:id])
    if @post.update(post_params)
      redirect_to post_path
    else
      render :edit
    end
  end

  def destroy
    @post = Post.find(params[:id])
    redirect_to root_path if @post.destroy
  end

  def game
  end

  def cooking
  end

  private

  def post_params
    params.require(:post).permit(:title, :description, :genre_id, :image).merge(user_id: current_user.id)
  end

end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/cooking.html.erb
<div class="header-top">
  <div class="header-inner">
    <h1><a href="https://appetizer-35960.herokuapp.com/">APPETIZER</a></h1>
    <div class="header-navi">
      <div class="content">
        <a href="https://appetizer-35960.herokuapp.com/">HOME</a>
      </div>
      <div class="content">
        <a href="#" id="lists">GAME</a>
      </div>
      <ul class="show-lists1 hidden" id="pull-down">
        <li id="lists"><%= link_to 'アプリ', posts_game_path %></li>
      </ul>
      <div class="content">
        <a href="#" id="lists1">COOKING</a>
      </div>
      <ul class="show-lists hidden" id="pull-down1">
        <li id="lists"><%= link_to 'ズボラレシピ', posts_cooking_path %></li>
      </ul>
      <div class="content">
        <a href="#", id="video">VIDEO</a>
      </div>
      <div class="contact" id="contact">
        <%= link_to 'CONTACT', new_user_registration_path %>
      </div>
    </div>
  </div>
</div>

<div class="main-intro">
  <div class="left-intro">
    <ul class="title">COOKING
      <li><%= link_to "ズボラレシピ", posts_cooking_path %></li>
    </ul>
  </div>

  <div class="rightintro">
    <div class="right-top">
      <p class="title">無限ピーマン</p>
      <div class="recipe">
        <%= image_tag "unlimited_p-men.jpg", size: "351x234", class: "foodimage" %>
        <div class="howto">
          <p class="description-top">材料</p>
          <p class="description-center">
            　　ピーマン：5, 6個<br>
            　　塩昆布　：ふたつまみ　　　<br>
            　　ごま油　：大さじ1</p>
          <p class="description-top">手順</p>
          <p class="description-bottom">
            　　1：ピーマンを縦半分に切り、横に細切りにします。<br>
            　　2：切ったピーマンと、塩昆布、ごま油をポリ袋に入れ混ぜます。<br>
            　　3：盛り付けて完成です。</p>
        </div>
      </div>
    </div>

    <div class="right-center">
      <p class="title">ちくわの磯辺マヨ焼き</p>
      <div class="recipe">
      <%= image_tag "tikuwanoisobeyaki.jpg", size: "351x234", class: "foodimage" %>
        <div class="howto">
          <p class="description-top">材料</p>
          <p class="description-center">
            　　ちくわ　　：4, 5本<br>
            　　マヨネーズ：大さじ3　　　　<br>
            　　青のり　　：大さじ1</p>
          <p class="description-top">手順</p>
          <p class="description-bottom">
            　　1：ちくわを約2cm幅に斜め切りします。<br>
            　　2：切ったちくわとマヨネーズと青のりをポリ袋に入れ混ぜあわせます。<br>
            　　3：アルミホイルを敷いて、オーブントースターで焼き色がつくまで5〜6分焼きます。<br>
            　　4：盛り付けて完成です。</p>
        </div>
      </div>
    </div>

    <div class="right-bottom">
      <p class="title">アボカドとサーモンのユッケ</p>
      <div class="recipe">
      <%= image_tag "abogadosa-mon.jpg", size: "351x234", class: "foodimage" %>
        <div class="howto">
          <p class="description-top">材料</p>
          <p class="description-center">
            　　サーモン　　　　：100g<br>
            　　アボガド　　　　：1/2個<br>
            　　醤油　　　　　　：大さじ1<br>
            　　コチュジャン　　：小さじ2<br>
            　　ごま油　　　　　：小さじ2<br>
            　　白いりごま　　　：小さじ1<br>
            　　チューブニンニク：小さじ1/2</p>
          <p class="description-top">手順</p>
          <p class="description-bottom">
            　　1：サーモンを1cm角に切ります。<br>
            　　2：アボカドも1cm角に切ります。<br>
            　　3：サーモン、アボガド、その他をポリ袋に入れ混ぜあわせます。<br>
            　　4：盛り付けて完成です。</p>
        </div>
      </div>
    </div>

  </div>

</div>



<div class="footer">
  <div class="footer-top">
  </div>
  <div class="footer-inner">
    <div class="inner-top">
      <span>APPETIZER, LCC</span>
    </div>
    <div class="inner-bottom">
      <p>自分も投稿したい方は、右上のCONTACTへ！</p>
    </div>
  </div>
</div>

app/views/posts/edit.html.erb
<div class="posts-sell-contents">
  <div class="posts-sell-main">
    <h2 class="posts-sell-title">商品の情報を入力</h2>
    <%= form_with model: @post, local: true do |f| %>

    <%# 商品画像 %>
    <div class="img-upload">
      <div class="weight-bold-text">
        商品画像
        <span class="indispensable">必須</span>
      </div>
      <div class="click-upload">
        <p>
          クリックしてファイルをアップロード
        </p>
        <%= f.file_field :image, id:"post-image" %>
      </div>
    </div>
    <%# /商品画像 %>
    <%# 商品名と商品説明 %>
    <div class="new-posts">
      <div class="weight-bold-text">
        商品名
        <span class="indispensable">必須</span>
      </div>
      <%= f.text_area :title, class:"posts-text", id:"post-name", placeholder:"商品名（必須 40文字まで)", maxlength:"40" %>
      <div class="posts-explain">
        <div class="weight-bold-text">
          商品の説明
          <span class="indispensable">必須</span>
        </div>
        <%= f.text_area :description, class:"posts-text", id:"post-info", placeholder:"商品の説明（必須 1,000文字まで）（色、素材、重さ、定価、注意点など）例）2010年頃に1万円で購入したジャケットです。ライトグレーで傷はありません。あわせやすいのでおすすめです。" ,rows:"7" ,maxlength:"1000" %>
      </div>
    </div>
    <%# /商品名と商品説明 %>

    <%# 商品の詳細 %>
    <div class="posts-detail">
      <div class="weight-bold-text">商品の詳細</div>
      <div class="form">
        <div class="weight-bold-text">
          カテゴリー
          <span class="indispensable">必須</span>
        </div>
        <%= f.collection_select(:genre_id, Genre.all, :id, :name, {}, {class:"select-box", id:"post-genre"}) %>
      </div>
    </div>
    <%# /商品の詳細 %>
    <div class="sell-btn-contents">
      <%= f.submit "変更する" ,class:"sell-btn" %>
      <%=link_to 'もどる', post_path, class:"back-btn" %>
    </div>
    <%# /下部ボタン %>
    <% end %>
  </div>
</div>

app/views/posts/game.html.erb
<div class="header-top">
  <div class="header-inner">
    <h1><a href="https://appetizer-35960.herokuapp.com/">APPETIZER</a></h1>
    <div class="header-navi">
      <div class="content">
        <a href="https://appetizer-35960.herokuapp.com/">HOME</a>
      </div>
      <div class="content">
        <a href="#" id="lists">GAME</a>
      </div>
      <ul class="show-lists1 hidden" id="pull-down">
        <li id="lists"><%= link_to 'アプリ', posts_game_path %></li>
      </ul>
      <div class="content">
        <a href="#" id="lists1">COOKING</a>
      </div>
      <ul class="show-lists hidden" id="pull-down1">
        <li id="lists"><%= link_to 'ズボラレシピ', posts_cooking_path %></li>
      </ul>
      <div class="content">
        <a href="#", id="video">VIDEO</a>
      </div>
      <div class="contact" id="contact">
        <%= link_to 'CONTACT', new_user_registration_path %>
      </div>
    </div>
  </div>
</div>

<div class="main-intro">
  <div class="left-intro">
    <ul class="title">GAME
      <li><%= link_to "アプリ", posts_game_path %></li>
    </ul>
  </div>

  <div class="rightintro">
    <div class="right-top">
      <p class="title">一人で飲みたい夜</p>
      <div class="recipe">
        <%= image_tag "alonesake.png", size: "351x351", class: "foodimage" %>
        <div class="howto">
          <p class="description-top">内容</p>
          <p class="description-center">
            　　一人で飲みたいおじさんの<a href="https://ja.game-cafe.net/topindex.php?id=hitorinomi">マインスイーパー</a>です。<br>
            　　他のおじさんがいない居酒屋を全て開けてください。<br>
            　　表示される数字は、隣接する居酒屋に隠れているおじさんの人数です。<br>
            　　フリックで居酒屋にマークできます。</p>
          <p class="description-top">コメント</p>
          <p class="description-bottom">
            　　他にも様々なゲームがあるので、おすすめです！<br>
            　　おじさんの絵が可愛くていいです！興味があれば是非！</p>
        </div>
      </div>
    </div>

    <div class="right-center">
      <p class="title">うたドン！</p>
      <div class="recipe">
      <%= image_tag "utadon.png", size: "351x351", class: "foodimage" %>
        <div class="howto">
          <p class="description-top">内容</p>
          <p class="description-center">
            　　<a href="https://apps.apple.com/jp/app/%E3%81%86%E3%81%9F%E3%83%89%E3%83%B3/id1201624046">うたドン！</a>というアプリです。<br>
            　　自分の年齢などから懐かしい歌をランダムで流し、早押しクイズが出来るアプリです。</p>
          <p class="description-top">コメント</p>
          <p class="description-bottom">
            　　ランキング参加もできるため、自分の実力を計ることができます！<br>
            　　2人で対戦もできるので、少人数での飲み会にもぴったり！<br>
            　　懐かしい曲を聞いて昔の事を思い出しながら、飲むお酒も乙ですね！<br></p>
        </div>
      </div>
    </div>

    <div class="right-bottom">
      <p class="title">怒るおじさん</p>
      <div class="recipe">
      <%= image_tag "angryojisan.png", size: "351x351", class: "foodimage" %>
        <div class="howto">
          <p class="description-top">内容</p>
          <p class="description-center">
            　　<a href="https://apps.apple.com/jp/app/%E6%80%92%E3%82%8B%E3%81%8A%E3%81%98%E3%81%95%E3%82%93/id529764262">怒るおじさん</a>というアプリです。<br>
            　　同じ顔のおじさんが何個も並べられていて、<br>
            　　タップすると一つだけ怒るようになっています。</p>
          <p class="description-top">コメント</p>
          <p class="description-bottom">
            　　シンプルなので、誰でも気軽に楽しめます！<br>
            　　怒るおじさんの絵が可愛くてついつい押してしまいます！<br>
            　　たまに「怒るおばさん」も出てくるので、それが出るまで続けるのも面白いです！</p>
        </div>
      </div>
    </div>

  </div>

</div>



<div class="footer">
  <div class="footer-top">
  </div>
  <div class="footer-inner">
    <div class="inner-top">
      <span>APPETIZER, LCC</span>
    </div>
    <div class="inner-bottom">
      <p>自分も投稿したい方は、右上のCONTACTへ！</p>
    </div>
  </div>
</div>

app/views/posts/index.html.erb
<div class="header-top">
  <div class="header-inner">
    <h1><a href="https://appetizer-35960.herokuapp.com/">APPETIZER</a></h1>
    <div class="header-navi">
      <div class="content">
        <a href="https://appetizer-35960.herokuapp.com/">HOME</a>
      </div>
      <div class="content">
        <a href="#" id="lists">GAME</a>
      </div>
      <ul class="show-lists1 hidden" id="pull-down">
        <li id="lists"><%= link_to 'アプリ', posts_game_path %></li>
      </ul>
      <div class="content">
        <a href="#" id="lists1">COOKING</a>
      </div>
      <ul class="show-lists hidden" id="pull-down1">
        <li id="lists"><%= link_to 'ズボラレシピ', posts_cooking_path %></li>
      </ul>
      <div class="content">
        <a href="#", id="video">VIDEO</a>
      </div>
      <div class="contact" id="contact">
        <%= link_to 'CONTACT', new_user_registration_path %>
      </div>
    </div>
  </div>
  <div class="header-center">
    <img id="image-left" src=""/>
    <p class="click-left" id="click-left">click</p>
    <h2>APPETIZERとは、家で一人でもお酒を楽しむことができる<br>アプリケーションです！</h2>
    <p class="click-right" id="click-right">click</p>
    <img id="image-appear" src=""/>
  </div>
</div>

<div class="main">

  <div class="main-top">
    <h1>About APPETIZER</h1>
    <p>APPETIZERとは、上記の通りです！<br>一人でもできる遊びやおすすめの簡単レシピなどを紹介するサイトです！！<br>
       宅飲みが流行している昨今の皆様の助けになれば幸いです！！！<br>不定期で更新しますので、たまにチェックをお願い致します！！！！</p>
  </div>

  <div class="main-center">
    <div class="left-image">
      <%= image_tag "topimage12.jpg", size: "469x312", id: "left-image"%>
    </div>
    <div class="right">
      <p class="name">世界の遊び</p>
      <p>世界の遊びを紹介します！<br>
          これであなたも海外旅行をしている気分に！？<br>
          是非楽しんでください！</p>
    </div>
  </div>

  <div class="main-bottom">
    <div class="left">
      <p class="name">簡単レシピ</p>
      <p>ズボラなあなたにぴったりな簡単レシピを紹介します。<br>
         僕自身もズボラなため、<br>
         調理時間5分以内！皿洗いなし！<br>
         の簡単レシピを紹介します！</p>
    </div>
    <div class="right-image">
      <%=image_tag "topimage11.jpg", size: "469x312"%>
    </div>
  </div>

</div>








<div class="footer">
  <div class="footer-top">
  </div>
  <div class="footer-inner">
    <div class="inner-top" id="inner-top"></div>
      <button id="button" class="button">ここをクリックすると、、、</button>
    <div class="inner-bottom" id="inner-bottom">
      <p>自分も投稿したい方は、右上のCONTACTへ！</p>
    </div>
  </div>
</div>

app/views/posts/new.html.erb
<div class="contents row">
  <div class="container">
    <h3>投稿する</h3>
    <%= form_with(model: @post, local: true) do |form| %>
      <%= form.text_field :title, placeholder: "Title" %>
      <%= form.text_area :description, placeholder: "Description", rows: "10" %>
      <%= form.label :Genre %><br />
      <%= form.collection_select(:genre_id, Genre.all, :id, :name, {}, {class:"select-box", id:"genre"}) %>

      <%# 商品画像 %>
        <div class="img-upload">
          <div class="weight-bold-text">
            商品画像
            <span class="indispensable">必須</span>
          </div>
          <div class="click-upload">
            <p>
              クリックしてファイルをアップロード
            </p>
            <%= form.file_field :image, id:"post-image" %>
          </div>
        </div>
        <%# /商品画像 %>

      <%= form.submit "投稿！" %>
    <% end %>
  </div>
</div>

app/views/posts/show.html.erb
<%# 商品の概要 %>
<div class="post-show">
  <div class="post-box">
    <h2 class="name">
      <%= @post.title %>
    </h2>
    <div class="post-img-content">
      <%= image_tag @post.image,class:"post-box-img" %>
    </div>
    <%= @post.description %>
    <div class="post-price-box">
      <span class="post-postage">
        <%= @post.genre.name %>
      </span>
      <%= @post.user.nickname %>
    </div>

      <% if current_user.id == @post.user_id %>
        <%= link_to "投稿の編集", edit_post_path, method: :get, class: "post-red-btn" %>
        <p class="or-text">or</p>
        <%= link_to "削除", post_path, method: :delete, class:"post-destroy" %>
      <% else %>
        <%#= link_to "購入画面に進む", post_purchase_records_path(@post.id) ,class:"post-red-btn"%>
      <% end %>
  </div>

  <div class="container">
    <% if user_signed_in? %>
      <%= form_with(model: [@post, @comment], local: true) do |form| %>
        <%= form.text_area :text, placeholder: "コメントする", rows: "2" %>
        <%= form.submit "送信" %>
      <% end %>
    <% else %>
      <strong><p>※※※ コメントの投稿には新規登録/ログインが必要です ※※※</p></strong>
    <% end %>
    <div class="comments">
      <h4>＜コメント一覧＞</h4>
      <% @comments.each do |comment| %>
        <p>
          <strong><%= link_to comment.user.nickname, "/users/#{comment.user_id}" %>：</strong>
          <%= comment.text %>
        </p>
      <% end %>
    </div>
  </div>

</div>